### ISSUE TITLE
"Show Custom Icons" list does not display custom icons used in mission support

### ISSUE THREAD

**Issue by no-goaway** [NPsim/P3#1]
P3 does not correctly display custom icons if they are under a "Mission" block.

![P3_1SZxv9aefs](https://user-images.githubusercontent.com/53493903/91646696-e0c60a80-ea06-11ea-871c-9244dbc1b786.png)
This is P3's output when I created a small test mission with three mission support bots (two with a custom icon) and with two normal bots (one also with a custom icon).

The test mission, template used, and a screenshot of the console output are contained here:
[icon.zip](https://github.com/NPsim/P3/files/5146024/icon.zip)
VirusTotal: [https://www.virustotal.com/gui/file/c9307482cc88478ee2e8ca373995c6c98454f09668bb4aee2d9bc02ad5f2cccb/detection](https://www.virustotal.com/gui/file/c9307482cc88478ee2e8ca373995c6c98454f09668bb4aee2d9bc02ad5f2cccb/detection)

**Comment by NPsim** [comment]
Fixed in version 2.1.0 by commit https://github.com/NPsim/P3/commit/9cdca64201b906c8095914e6cb40e8ac8964f092
